# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_denormalize}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Logan Raarup"]
  s.date = %q{2012-02-05}
  s.description = %q{Helper module for denormalizing association attributes in Mongoid models.}
  s.email = %q{logan@logan.dk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "lib/mongoid_denormalize.rb",
    "lib/railties/denormalize.rake",
    "lib/railties/railtie.rb"
  ]
  s.homepage = %q{http://github.com/logandk/mongoid_denormalize}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Mongoid denormalization helper.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 2.1.9"])
    else
      s.add_dependency(%q<mongoid>, [">= 2.1.9"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 2.1.9"])
  end
end

